# Generated by Django 2.2.4 on 2019-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('BTS_type', models.CharField(blank=True, max_length=100, null=True)),
                ('site_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('geotech_file', models.FileField(blank=True, null=True, upload_to='files/Project/geotech/%Y/%m/%d/')),
                ('access_letter', models.FileField(blank=True, null=True, upload_to='files/Project/accessletters/%Y/%m/%d/')),
                ('approved_drawing', models.FileField(blank=True, null=True, upload_to='files/Project/approveddrawings/%Y/%m/%d/')),
                ('final_acceptance_cert', models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/finalcert/%Y/%m/%d/')),
                ('final_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
