# Generated by Django 2.2.4 on 2019-08-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_btssite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BtsSite',
            new_name='Site',
        ),
    ]
